################################################################################

# This Makefile generated by GoMakeGen 1.0.0 using next command:
# gomakegen --dep --verbose .
#
# More info: https://kaos.sh/gomakegen

################################################################################

.DEFAULT_GOAL := help
.PHONY = fmt git-config deps deps-test test dep-init dep-update help

################################################################################

git-config: ## Configure git redirects for stable import path services
	git config --global http.https://pkg.re.followRedirects true

deps: git-config dep-update ## Download dependencies

deps-test: ## Download dependencies for tests
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v pkg.re/check.v1

test: ## Run tests
	go test -v -covermode=count .

dep-init: ## Initialize dep workspace
	which dep &>/dev/null || go get -u -v github.com/golang/dep/cmd/dep
	dep init

dep-update: ## Update packages and dependencies through dep
	which dep &>/dev/null || go get -u -v github.com/golang/dep/cmd/dep
	test -s Gopkg.toml || dep init
	dep ensure -update

fmt: ## Format source code with gofmt
	find . -name "*.go" -exec gofmt -s -w {} \;

help: ## Show this info
	@echo -e '\nSupported targets:\n'
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[33m%-12s\033[0m %s\n", $$1, $$2}'
	@echo -e ''

################################################################################
